services:
  sessionstealerapi:
    image: sessionstealerapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /root/uploads:/root/uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

